# Week 2 — Day 2: Baseline evaluation (BLEU / ROUGE)

Tasks:
- Set up evaluation metrics for captioning: BLEU, ROUGE
- Run zero-shot BLIP over a larger validation subset (200-500 images) and compute metric scores

Deliverable: baseline evaluation report (metric scores table) for zero-shot BLIP on the Flickr8k
validation subset.

### 1. Load BLIP and pick a 300-image validation subset

In [1]:
import os
import time
import pandas as pd
import torch
import evaluate
from PIL import Image
from tqdm import tqdm
from transformers import BlipProcessor, BlipForConditionalGeneration

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

model_name = "Salesforce/blip-image-captioning-base"
processor = BlipProcessor.from_pretrained(model_name)
model = BlipForConditionalGeneration.from_pretrained(model_name).to(device)
model.eval()

captions_path = '../data/captions.txt'
img_dir = '../data/Images'

df = pd.read_csv(captions_path)
df.columns = ['image', 'caption']

VAL_SIZE = 300
val_images = df['image'].drop_duplicates().sample(VAL_SIZE, random_state=123).tolist()
# all 5 ground-truth captions per image, for multi-reference scoring
references = [df[df['image'] == img]['caption'].tolist() for img in val_images]
print(f"Validation subset: {len(val_images)} images, {sum(len(r) for r in references)} reference captions")

Using device: cpu

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/473 [00:00<?, ?it/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  990MB

model.safetensors: downloading bytes:           |  0.00B

Validation subset: 300 images, 1500 reference captions

### 2. Generate zero-shot captions for the whole subset

In [2]:
@torch.no_grad()
def generate_caption(img_path):
    image = Image.open(img_path).convert('RGB')
    inputs = processor(images=image, return_tensors="pt").to(device)
    out = model.generate(**inputs, max_new_tokens=30)
    return processor.decode(out[0], skip_special_tokens=True)

start = time.time()
predictions = []
for img_name in tqdm(val_images):
    pred = generate_caption(os.path.join(img_dir, img_name))
    predictions.append(pred)
elapsed = time.time() - start
print(f"Generated {len(predictions)} captions in {elapsed:.1f}s ({elapsed/len(predictions):.2f}s/image)")

  0%|          | 0/300 [00:00<?, ?it/s]

  0%|          | 1/300 [00:03<17:47,  3.57s/it]

  1%|          | 2/300 [00:07<18:07,  3.65s/it]

  1%|          | 3/300 [00:10<17:26,  3.53s/it]

  1%|▏         | 4/300 [00:13<16:07,  3.27s/it]

  2%|▏         | 5/300 [00:16<15:30,  3.15s/it]

  2%|▏         | 6/300 [00:19<15:06,  3.08s/it]

  2%|▏         | 7/300 [00:22<14:58,  3.07s/it]

  3%|▎         | 8/300 [00:25<14:43,  3.03s/it]

  3%|▎         | 9/300 [00:28<14:25,  2.97s/it]

  3%|▎         | 10/300 [00:31<14:11,  2.94s/it]

  4%|▎         | 11/300 [00:34<14:30,  3.01s/it]

  4%|▍         | 12/300 [00:37<14:01,  2.92s/it]

  4%|▍         | 13/300 [00:40<14:25,  3.02s/it]

  5%|▍         | 14/300 [00:43<14:33,  3.05s/it]

  5%|▌         | 15/300 [00:46<15:05,  3.18s/it]

  5%|▌         | 16/300 [00:49<14:49,  3.13s/it]

  6%|▌         | 17/300 [00:52<14:44,  3.13s/it]

  6%|▌         | 18/300 [00:56<14:49,  3.15s/it]

  6%|▋         | 19/300 [00:59<14:32,  3.11s/it]

  7%|▋         | 20/300 [01:02<14:28,  3.10s/it]

  7%|▋         | 21/300 [01:05<14:46,  3.18s/it]

  7%|▋         | 22/300 [01:08<14:19,  3.09s/it]

  8%|▊         | 23/300 [01:13<16:45,  3.63s/it]

  8%|▊         | 24/300 [01:16<15:59,  3.47s/it]

  8%|▊         | 25/300 [01:19<15:48,  3.45s/it]

  9%|▊         | 26/300 [01:23<15:41,  3.44s/it]

  9%|▉         | 27/300 [01:26<15:08,  3.33s/it]

  9%|▉         | 28/300 [01:29<14:20,  3.16s/it]

 10%|▉         | 29/300 [01:31<13:46,  3.05s/it]

 10%|█         | 30/300 [01:34<13:28,  3.00s/it]

 10%|█         | 31/300 [01:37<13:05,  2.92s/it]

 11%|█         | 32/300 [01:40<12:54,  2.89s/it]

 11%|█         | 33/300 [01:43<12:43,  2.86s/it]

 11%|█▏        | 34/300 [01:46<12:49,  2.89s/it]

 12%|█▏        | 35/300 [01:49<13:01,  2.95s/it]

 12%|█▏        | 36/300 [01:52<12:48,  2.91s/it]

 12%|█▏        | 37/300 [01:54<12:28,  2.85s/it]

 13%|█▎        | 38/300 [01:57<12:30,  2.87s/it]

 13%|█▎        | 39/300 [02:00<12:13,  2.81s/it]

 13%|█▎        | 40/300 [02:03<12:20,  2.85s/it]

 14%|█▎        | 41/300 [02:06<13:08,  3.04s/it]

 14%|█▍        | 42/300 [02:09<13:01,  3.03s/it]

 14%|█▍        | 43/300 [02:12<13:10,  3.07s/it]

 15%|█▍        | 44/300 [02:15<12:49,  3.00s/it]

 15%|█▌        | 45/300 [02:19<13:28,  3.17s/it]

 15%|█▌        | 46/300 [02:22<13:15,  3.13s/it]

 16%|█▌        | 47/300 [02:25<13:02,  3.09s/it]

 16%|█▌        | 48/300 [02:28<12:45,  3.04s/it]

 16%|█▋        | 49/300 [02:31<12:21,  2.95s/it]

 17%|█▋        | 50/300 [02:33<12:11,  2.93s/it]

 17%|█▋        | 51/300 [02:37<12:31,  3.02s/it]

 17%|█▋        | 52/300 [02:40<12:15,  2.97s/it]

 18%|█▊        | 53/300 [02:43<12:32,  3.05s/it]

 18%|█▊        | 54/300 [02:48<14:41,  3.58s/it]

 18%|█▊        | 55/300 [02:54<17:45,  4.35s/it]

 19%|█▊        | 56/300 [03:00<20:34,  5.06s/it]

 19%|█▉        | 57/300 [03:05<19:20,  4.78s/it]

 19%|█▉        | 58/300 [03:09<18:29,  4.58s/it]

 20%|█▉        | 59/300 [03:12<17:07,  4.26s/it]

 20%|██        | 60/300 [03:16<15:53,  3.97s/it]

 20%|██        | 61/300 [03:19<15:11,  3.81s/it]

 21%|██        | 62/300 [03:23<15:19,  3.86s/it]

 21%|██        | 63/300 [03:27<15:53,  4.03s/it]

 21%|██▏       | 64/300 [03:30<14:49,  3.77s/it]

 22%|██▏       | 65/300 [03:34<14:10,  3.62s/it]

 22%|██▏       | 66/300 [03:37<13:58,  3.58s/it]

 22%|██▏       | 67/300 [03:41<14:02,  3.62s/it]

 23%|██▎       | 68/300 [03:44<13:17,  3.44s/it]

 23%|██▎       | 69/300 [03:47<13:03,  3.39s/it]

 23%|██▎       | 70/300 [03:51<12:56,  3.38s/it]

 24%|██▎       | 71/300 [03:54<13:05,  3.43s/it]

 24%|██▍       | 72/300 [03:58<13:22,  3.52s/it]

 24%|██▍       | 73/300 [04:02<13:25,  3.55s/it]

 25%|██▍       | 74/300 [04:05<13:01,  3.46s/it]

 25%|██▌       | 75/300 [04:10<14:50,  3.96s/it]

 25%|██▌       | 76/300 [04:17<18:28,  4.95s/it]

 26%|██▌       | 77/300 [04:24<20:18,  5.46s/it]

 26%|██▌       | 78/300 [04:29<20:11,  5.46s/it]

 26%|██▋       | 79/300 [04:34<19:09,  5.20s/it]

 27%|██▋       | 80/300 [04:37<17:18,  4.72s/it]

 27%|██▋       | 81/300 [04:41<15:27,  4.24s/it]

 27%|██▋       | 82/300 [04:44<14:24,  3.97s/it]

 28%|██▊       | 83/300 [04:48<14:02,  3.88s/it]

 28%|██▊       | 84/300 [04:51<13:59,  3.88s/it]

 28%|██▊       | 85/300 [04:55<13:25,  3.75s/it]

 29%|██▊       | 86/300 [04:58<13:09,  3.69s/it]

 29%|██▉       | 87/300 [05:02<12:38,  3.56s/it]

 29%|██▉       | 88/300 [05:06<12:55,  3.66s/it]

 30%|██▉       | 89/300 [05:09<12:55,  3.68s/it]

 30%|███       | 90/300 [05:13<13:10,  3.76s/it]

 30%|███       | 91/300 [05:18<14:15,  4.10s/it]

 31%|███       | 92/300 [05:22<13:58,  4.03s/it]

 31%|███       | 93/300 [05:26<13:47,  4.00s/it]

 31%|███▏      | 94/300 [05:30<13:31,  3.94s/it]

 32%|███▏      | 95/300 [05:34<13:21,  3.91s/it]

 32%|███▏      | 96/300 [05:37<12:50,  3.78s/it]

 32%|███▏      | 97/300 [05:42<13:58,  4.13s/it]

 33%|███▎      | 98/300 [05:46<13:52,  4.12s/it]

 33%|███▎      | 99/300 [05:51<14:10,  4.23s/it]

 33%|███▎      | 100/300 [05:54<13:07,  3.94s/it]

 34%|███▎      | 101/300 [05:59<14:06,  4.25s/it]

 34%|███▍      | 102/300 [06:03<14:10,  4.29s/it]

 34%|███▍      | 103/300 [06:08<14:37,  4.46s/it]

 35%|███▍      | 104/300 [06:11<13:21,  4.09s/it]

 35%|███▌      | 105/300 [06:14<12:10,  3.75s/it]

 35%|███▌      | 106/300 [06:17<11:23,  3.52s/it]

 36%|███▌      | 107/300 [06:21<11:24,  3.55s/it]

 36%|███▌      | 108/300 [06:24<11:22,  3.56s/it]

 36%|███▋      | 109/300 [06:29<12:12,  3.84s/it]

 37%|███▋      | 110/300 [06:33<12:02,  3.80s/it]

 37%|███▋      | 111/300 [06:36<12:00,  3.81s/it]

 37%|███▋      | 112/300 [06:40<11:46,  3.76s/it]

 38%|███▊      | 113/300 [06:44<11:42,  3.76s/it]

 38%|███▊      | 114/300 [06:49<12:52,  4.15s/it]

 38%|███▊      | 115/300 [06:55<14:18,  4.64s/it]

 39%|███▊      | 116/300 [06:59<14:15,  4.65s/it]

 39%|███▉      | 117/300 [07:04<14:06,  4.62s/it]

 39%|███▉      | 118/300 [07:08<13:14,  4.37s/it]

 40%|███▉      | 119/300 [07:11<12:06,  4.01s/it]

 40%|████      | 120/300 [07:14<11:19,  3.77s/it]

 40%|████      | 121/300 [07:18<10:55,  3.66s/it]

 41%|████      | 122/300 [07:21<10:27,  3.53s/it]

 41%|████      | 123/300 [07:24<10:00,  3.39s/it]

 41%|████▏     | 124/300 [07:27<09:43,  3.31s/it]

 42%|████▏     | 125/300 [07:30<09:51,  3.38s/it]

 42%|████▏     | 126/300 [07:34<09:38,  3.33s/it]

 42%|████▏     | 127/300 [07:37<09:12,  3.19s/it]

 43%|████▎     | 128/300 [07:40<09:29,  3.31s/it]

 43%|████▎     | 129/300 [07:43<09:27,  3.32s/it]

H:\intern_ICDA\voice_agent\.venv\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\umer\.cache\huggingface\hub\models--Salesforce--blip-image-captioning-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

 43%|████▎     | 130/300 [07:47<09:22,  3.31s/it]

 44%|████▎     | 131/300 [07:50<09:27,  3.36s/it]

 44%|████▍     | 132/300 [07:54<09:20,  3.34s/it]

 44%|████▍     | 133/300 [07:56<08:35,  3.08s/it]

 45%|████▍     | 134/300 [07:59<08:38,  3.12s/it]

 45%|████▌     | 135/300 [08:02<08:39,  3.15s/it]

 45%|████▌     | 136/300 [08:05<08:28,  3.10s/it]

 46%|████▌     | 137/300 [08:09<08:40,  3.19s/it]

 46%|████▌     | 138/300 [08:12<08:15,  3.06s/it]

 46%|████▋     | 139/300 [08:15<08:07,  3.03s/it]

 47%|████▋     | 140/300 [08:18<08:14,  3.09s/it]

 47%|████▋     | 141/300 [08:21<08:29,  3.21s/it]

 47%|████▋     | 142/300 [08:25<08:38,  3.28s/it]

 48%|████▊     | 143/300 [08:28<08:33,  3.27s/it]

 48%|████▊     | 144/300 [08:31<08:22,  3.22s/it]

 48%|████▊     | 145/300 [08:34<07:58,  3.09s/it]

 49%|████▊     | 146/300 [08:37<07:55,  3.09s/it]

 49%|████▉     | 147/300 [08:40<07:39,  3.01s/it]

 49%|████▉     | 148/300 [08:43<07:32,  2.98s/it]

 50%|████▉     | 149/300 [08:46<07:33,  3.00s/it]

 50%|█████     | 150/300 [08:49<07:41,  3.07s/it]

 50%|█████     | 151/300 [08:52<07:18,  2.94s/it]

 51%|█████     | 152/300 [08:55<07:17,  2.96s/it]

 51%|█████     | 153/300 [08:58<07:19,  2.99s/it]

 51%|█████▏    | 154/300 [09:01<07:10,  2.95s/it]

 52%|█████▏    | 155/300 [09:05<08:21,  3.46s/it]

 52%|█████▏    | 156/300 [09:08<07:46,  3.24s/it]

 52%|█████▏    | 157/300 [09:11<07:16,  3.05s/it]

 53%|█████▎    | 158/300 [09:13<07:03,  2.98s/it]

 53%|█████▎    | 159/300 [09:16<06:58,  2.97s/it]

 53%|█████▎    | 160/300 [09:19<06:40,  2.86s/it]

 54%|█████▎    | 161/300 [09:22<06:29,  2.80s/it]

 54%|█████▍    | 162/300 [09:24<06:25,  2.79s/it]

 54%|█████▍    | 163/300 [09:27<06:20,  2.78s/it]

 55%|█████▍    | 164/300 [09:30<06:22,  2.81s/it]

 55%|█████▌    | 165/300 [09:32<06:07,  2.72s/it]

 55%|█████▌    | 166/300 [09:35<06:03,  2.72s/it]

 56%|█████▌    | 167/300 [09:38<06:10,  2.79s/it]

 56%|█████▌    | 168/300 [09:41<06:01,  2.74s/it]

 56%|█████▋    | 169/300 [09:44<06:08,  2.82s/it]

 57%|█████▋    | 170/300 [09:47<06:07,  2.82s/it]

 57%|█████▋    | 171/300 [09:49<06:01,  2.80s/it]

 57%|█████▋    | 172/300 [09:52<06:06,  2.86s/it]

 58%|█████▊    | 173/300 [09:55<06:08,  2.90s/it]

 58%|█████▊    | 174/300 [09:58<05:55,  2.82s/it]

 58%|█████▊    | 175/300 [10:01<05:51,  2.81s/it]

 59%|█████▊    | 176/300 [10:04<05:55,  2.87s/it]

 59%|█████▉    | 177/300 [10:07<05:48,  2.83s/it]

 59%|█████▉    | 178/300 [10:09<05:31,  2.72s/it]

 60%|█████▉    | 179/300 [10:12<05:27,  2.71s/it]

 60%|██████    | 180/300 [10:15<05:36,  2.81s/it]

 60%|██████    | 181/300 [10:18<05:37,  2.84s/it]

 61%|██████    | 182/300 [10:21<05:37,  2.86s/it]

 61%|██████    | 183/300 [10:23<05:26,  2.79s/it]

 61%|██████▏   | 184/300 [10:27<05:51,  3.03s/it]

 62%|██████▏   | 185/300 [10:29<05:37,  2.94s/it]

 62%|██████▏   | 186/300 [10:32<05:30,  2.90s/it]

 62%|██████▏   | 187/300 [10:35<05:31,  2.93s/it]

 63%|██████▎   | 188/300 [10:38<05:32,  2.97s/it]

 63%|██████▎   | 189/300 [10:41<05:24,  2.93s/it]

 63%|██████▎   | 190/300 [10:45<05:46,  3.15s/it]

 64%|██████▎   | 191/300 [10:47<05:26,  2.99s/it]

 64%|██████▍   | 192/300 [10:50<05:21,  2.98s/it]

 64%|██████▍   | 193/300 [10:53<05:14,  2.94s/it]

 65%|██████▍   | 194/300 [10:56<05:07,  2.90s/it]

 65%|██████▌   | 195/300 [10:59<04:57,  2.83s/it]

 65%|██████▌   | 196/300 [11:01<04:48,  2.77s/it]

 66%|██████▌   | 197/300 [11:04<04:42,  2.75s/it]

 66%|██████▌   | 198/300 [11:07<04:50,  2.84s/it]

 66%|██████▋   | 199/300 [11:10<04:41,  2.79s/it]

 67%|██████▋   | 200/300 [11:13<04:40,  2.81s/it]

 67%|██████▋   | 201/300 [11:15<04:34,  2.77s/it]

 67%|██████▋   | 202/300 [11:18<04:28,  2.74s/it]

 68%|██████▊   | 203/300 [11:21<04:31,  2.80s/it]

 68%|██████▊   | 204/300 [11:24<04:37,  2.89s/it]

 68%|██████▊   | 205/300 [11:28<05:04,  3.21s/it]

 69%|██████▊   | 206/300 [11:31<05:08,  3.28s/it]

 69%|██████▉   | 207/300 [11:35<05:00,  3.23s/it]

 69%|██████▉   | 208/300 [11:37<04:48,  3.13s/it]

 70%|██████▉   | 209/300 [11:40<04:30,  2.97s/it]

 70%|███████   | 210/300 [11:43<04:33,  3.04s/it]

 70%|███████   | 211/300 [11:46<04:19,  2.92s/it]

 71%|███████   | 212/300 [11:49<04:14,  2.89s/it]

 71%|███████   | 213/300 [11:52<04:15,  2.93s/it]

 71%|███████▏  | 214/300 [11:55<04:08,  2.89s/it]

 72%|███████▏  | 215/300 [11:57<04:01,  2.84s/it]

 72%|███████▏  | 216/300 [12:00<03:58,  2.84s/it]

 72%|███████▏  | 217/300 [12:03<03:52,  2.80s/it]

 73%|███████▎  | 218/300 [12:06<03:47,  2.78s/it]

 73%|███████▎  | 219/300 [12:08<03:43,  2.76s/it]

 73%|███████▎  | 220/300 [12:11<03:38,  2.73s/it]

 74%|███████▎  | 221/300 [12:14<03:41,  2.80s/it]

 74%|███████▍  | 222/300 [12:16<03:33,  2.74s/it]

 74%|███████▍  | 223/300 [12:19<03:29,  2.72s/it]

 75%|███████▍  | 224/300 [12:22<03:25,  2.70s/it]

 75%|███████▌  | 225/300 [12:26<03:51,  3.09s/it]

 75%|███████▌  | 226/300 [12:29<03:52,  3.14s/it]

 76%|███████▌  | 227/300 [12:32<03:50,  3.16s/it]

 76%|███████▌  | 228/300 [12:35<03:38,  3.04s/it]

 76%|███████▋  | 229/300 [12:38<03:25,  2.90s/it]

 77%|███████▋  | 230/300 [12:40<03:16,  2.81s/it]

 77%|███████▋  | 231/300 [12:43<03:13,  2.81s/it]

 77%|███████▋  | 232/300 [12:46<03:11,  2.82s/it]

 78%|███████▊  | 233/300 [12:49<03:09,  2.83s/it]

 78%|███████▊  | 234/300 [12:51<02:59,  2.72s/it]

 78%|███████▊  | 235/300 [12:54<03:02,  2.80s/it]

 79%|███████▊  | 236/300 [12:58<03:12,  3.01s/it]

 79%|███████▉  | 237/300 [13:00<03:04,  2.93s/it]

 79%|███████▉  | 238/300 [13:03<02:56,  2.85s/it]

 80%|███████▉  | 239/300 [13:06<02:53,  2.85s/it]

 80%|████████  | 240/300 [13:09<02:50,  2.84s/it]

 80%|████████  | 241/300 [13:11<02:43,  2.76s/it]

 81%|████████  | 242/300 [13:14<02:46,  2.88s/it]

 81%|████████  | 243/300 [13:17<02:42,  2.85s/it]

 81%|████████▏ | 244/300 [13:20<02:40,  2.86s/it]

 82%|████████▏ | 245/300 [13:23<02:37,  2.86s/it]

 82%|████████▏ | 246/300 [13:27<02:46,  3.08s/it]

 82%|████████▏ | 247/300 [13:30<02:50,  3.22s/it]

 83%|████████▎ | 248/300 [13:34<02:52,  3.32s/it]

 83%|████████▎ | 249/300 [13:37<02:43,  3.22s/it]

 83%|████████▎ | 250/300 [13:39<02:35,  3.12s/it]

 84%|████████▎ | 251/300 [13:42<02:27,  3.01s/it]

 84%|████████▍ | 252/300 [13:45<02:20,  2.92s/it]

 84%|████████▍ | 253/300 [13:48<02:15,  2.89s/it]

 85%|████████▍ | 254/300 [13:51<02:11,  2.85s/it]

 85%|████████▌ | 255/300 [13:54<02:14,  2.99s/it]

 85%|████████▌ | 256/300 [13:57<02:13,  3.04s/it]

 86%|████████▌ | 257/300 [14:00<02:12,  3.07s/it]

 86%|████████▌ | 258/300 [14:03<02:04,  2.96s/it]

 86%|████████▋ | 259/300 [14:06<01:58,  2.90s/it]

 87%|████████▋ | 260/300 [14:08<01:52,  2.81s/it]

 87%|████████▋ | 261/300 [14:11<01:48,  2.78s/it]

 87%|████████▋ | 262/300 [14:14<01:44,  2.76s/it]

 88%|████████▊ | 263/300 [14:16<01:42,  2.77s/it]

 88%|████████▊ | 264/300 [14:19<01:40,  2.78s/it]

 88%|████████▊ | 265/300 [14:22<01:34,  2.71s/it]

 89%|████████▊ | 266/300 [14:25<01:41,  2.97s/it]

 89%|████████▉ | 267/300 [14:29<01:45,  3.20s/it]

 89%|████████▉ | 268/300 [14:32<01:39,  3.11s/it]

 90%|████████▉ | 269/300 [14:35<01:40,  3.23s/it]

 90%|█████████ | 270/300 [14:38<01:32,  3.09s/it]

 90%|█████████ | 271/300 [14:41<01:29,  3.07s/it]

 91%|█████████ | 272/300 [14:44<01:24,  3.01s/it]

 91%|█████████ | 273/300 [14:47<01:19,  2.94s/it]

 91%|█████████▏| 274/300 [14:50<01:14,  2.85s/it]

 92%|█████████▏| 275/300 [14:52<01:09,  2.80s/it]

 92%|█████████▏| 276/300 [14:55<01:10,  2.92s/it]

 92%|█████████▏| 277/300 [14:58<01:07,  2.95s/it]

 93%|█████████▎| 278/300 [15:01<01:04,  2.91s/it]

 93%|█████████▎| 279/300 [15:04<00:59,  2.85s/it]

 93%|█████████▎| 280/300 [15:07<00:58,  2.91s/it]

 94%|█████████▎| 281/300 [15:10<00:53,  2.83s/it]

 94%|█████████▍| 282/300 [15:12<00:49,  2.76s/it]

 94%|█████████▍| 283/300 [15:15<00:48,  2.84s/it]

 95%|█████████▍| 284/300 [15:18<00:44,  2.75s/it]

 95%|█████████▌| 285/300 [15:20<00:40,  2.70s/it]

 95%|█████████▌| 286/300 [15:24<00:39,  2.82s/it]

 96%|█████████▌| 287/300 [15:28<00:41,  3.17s/it]

 96%|█████████▌| 288/300 [15:31<00:40,  3.41s/it]

 96%|█████████▋| 289/300 [15:35<00:36,  3.33s/it]

 97%|█████████▋| 290/300 [15:37<00:31,  3.16s/it]

 97%|█████████▋| 291/300 [15:40<00:27,  3.02s/it]

 97%|█████████▋| 292/300 [15:43<00:23,  3.00s/it]

 98%|█████████▊| 293/300 [15:46<00:20,  2.92s/it]

 98%|█████████▊| 294/300 [15:48<00:16,  2.82s/it]

 98%|█████████▊| 295/300 [15:51<00:14,  2.88s/it]

 99%|█████████▊| 296/300 [15:54<00:11,  2.80s/it]

 99%|█████████▉| 297/300 [15:57<00:08,  2.85s/it]

 99%|█████████▉| 298/300 [16:00<00:05,  2.86s/it]

100%|█████████▉| 299/300 [16:03<00:02,  2.81s/it]

100%|██████████| 300/300 [16:05<00:00,  2.79s/it]

100%|██████████| 300/300 [16:05<00:00,  3.22s/it]

Generated 300 captions in 965.8s (3.22s/image)

### 3. Compute BLEU and ROUGE against the 5 human references per image

In [3]:
bleu_metric = evaluate.load("sacrebleu")
rouge_metric = evaluate.load("rouge")

bleu_result = bleu_metric.compute(predictions=predictions, references=references)
rouge_result = rouge_metric.compute(predictions=predictions, references=references)

scores_table = pd.DataFrame([
    {"metric": "BLEU (sacrebleu)", "score": bleu_result["score"]},
    {"metric": "ROUGE-1", "score": rouge_result["rouge1"] * 100},
    {"metric": "ROUGE-2", "score": rouge_result["rouge2"] * 100},
    {"metric": "ROUGE-L", "score": rouge_result["rougeL"] * 100},
])
scores_table

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

             metric      score
0  BLEU (sacrebleu)  16.656270
1           ROUGE-1  50.194672
2           ROUGE-2  26.643420
3           ROUGE-L  48.080152

### 4. Save the report

In [4]:
os.makedirs('../data/processed', exist_ok=True)
scores_table.to_csv('../data/processed/week2_baseline_eval_scores.csv', index=False)

report_df = pd.DataFrame({
    "image": val_images,
    "predicted_caption": predictions,
    "reference_captions": ["; ".join(r) for r in references],
})
report_df.to_csv('../data/processed/week2_baseline_eval_predictions.csv', index=False)
print("Saved scores and per-image predictions to data/processed/")
report_df.head(10)

Saved scores and per-image predictions to data/processed/

,image,predicted_caption,reference_captions
0,2304374703_555195d8d5.jpg,a dog playing with a ball in the snow,A brown dog plays with a bright orange ball in...
1,3497238310_2abde3965d.jpg,a man and a boy playing basketball in a gym,A group of men stand in a gymnasium with a bas...
2,3434526008_02359881a0.jpg,a skateboarder is doing a trick on a ramp,A man in a sleeveless shirt is performing an a...
3,3349258288_5300c40430.jpg,a man on a skateboard,A guy gettin some air on a skateboard; A man r...
4,369360998_ba56fb436f.jpg,a woman kneeling in the snow,A blonde woman with a red backpack in the snow...
5,3501206996_477be0f318.jpg,a young boy playing soccer,A child in a brown coat is kicking a soccer ba...
6,3677329561_fa3e1fdcf9.jpg,a dog with a frumbent,A dog is being washed by two little girls .; t...
7,1917265421_aeccf1ca38.jpg,a group of people,Children participate in a sport involving swin...
8,2819254573_9ecb5f4d5e.jpg,a boy in a chair,A child is yelling whilst on a roller coaster;...
9,3327563443_870a33f748.jpg,a woman wearing a hat,A woman in a white baseball hat reveals her ta...

### Notes

- Scores are computed zero-shot (no fine-tuning yet) — this is the **baseline** the Week 2 Day 3-4
  fine-tuning experiments need to beat.
- BLEU/ROUGE against 5 free-form human references per image are inherently noisy (valid captions can
  describe an image very differently and still score low n-gram overlap), so treat these as a
  reference point rather than an absolute quality measure — the qualitative review from Day 1 matters
  just as much.
- This same generation + scoring loop is reused in Day 4 to compare fine-tuning configurations.